# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.resize(321, 287)
        self.label = QtWidgets.QLabel(Help)
        self.label.setGeometry(QtCore.QRect(80, 10, 191, 41))
        self.label.setStyleSheet("font: 75 24pt \"Arial\";\n"
"color: rgb(255, 38, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Help)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 151, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Help)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 231, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Help)
        self.label_4.setGeometry(QtCore.QRect(40, 110, 221, 141))
        self.label_4.setStyleSheet("image: url(:/log/information.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "Help"))
        self.label.setText(_translate("Help", "H28 Tester 3"))
        self.label_2.setText(_translate("Help", "作者：侯龙"))
        self.label_3.setText(_translate("Help", "邮箱：long2.hou@luxshare-ict.com"))
from Resource.Img import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Help = QtWidgets.QWidget()
    ui = Ui_Help()
    ui.setupUi(Help)
    Help.show()
    sys.exit(app.exec_())
