# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1366, 668)
        Form.setMinimumSize(QtCore.QSize(1366, 668))
        Form.setMaximumSize(QtCore.QSize(1366, 668))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("border:0px inset black;\n"
"background-color:#8EE5EE")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(380, 10, 541, 91))
        self.label.setStyleSheet("color:rgb(255, 75, 31);\n"
"font: 75 36pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(940, 15, 351, 81))
        self.label_2.setStyleSheet("image: url(:/log/luxshare2.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 361, 91))
        self.label_3.setStyleSheet("font: 18pt \"Arial\";\n"
"color:#F8F8FF;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(40, -1, 40, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.port_setting = QtWidgets.QWidget()
        self.port_setting.setObjectName("port_setting")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.port_setting)
        self.horizontalLayout_2.setContentsMargins(30, 10, 30, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.port_setting)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setRowCount(14)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2.setStretch(0, 5)
        self.tabWidget.addTab(self.port_setting, "")
        self.mes_setting = QtWidgets.QWidget()
        self.mes_setting.setObjectName("mes_setting")
        self.label_4 = QtWidgets.QLabel(self.mes_setting)
        self.label_4.setGeometry(QtCore.QRect(60, 40, 131, 21))
        self.label_4.setStyleSheet("font: 75 18pt \"Arial\";\n"
"color: rgb(255, 38, 0);")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.mes_setting)
        self.pushButton.setGeometry(QtCore.QRect(190, 30, 113, 41))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.mes_setting)
        self.groupBox_2.setGeometry(QtCore.QRect(480, 110, 321, 281))
        self.groupBox_2.setStyleSheet("font: 75 18pt \"Arial\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.mes_setting)
        self.groupBox_3.setGeometry(QtCore.QRect(880, 30, 361, 361))
        self.groupBox_3.setStyleSheet("font: 75 18pt \"Arial\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.mes_setting)
        self.groupBox_4.setGeometry(QtCore.QRect(60, 110, 321, 281))
        self.groupBox_4.setStyleSheet("font: 75 18pt \"Arial\";")
        self.groupBox_4.setObjectName("groupBox_4")
        self.tabWidget.addTab(self.mes_setting, "")
        self.other_setting = QtWidgets.QWidget()
        self.other_setting.setObjectName("other_setting")
        self.tabWidget.addTab(self.other_setting, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setStyleSheet("QPushButton{\n"
"    background-color:#FFEFD5;\n"
"    border-radius:6px;\n"
"    border:1px inset black;\n"
"    width:150px;\n"
"    height:40px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:#FFEF15;\n"
"    border-radius:6px;\n"
"    border:2px outset black;\n"
"    width:150px;\n"
"    height:40px;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(self.widget_3)
        self.btn_save.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/log/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon)
        self.btn_save.setIconSize(QtCore.QSize(40, 40))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_cancel = QtWidgets.QPushButton(self.widget_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/log/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon1)
        self.btn_cancel.setIconSize(QtCore.QSize(30, 30))
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "H28 SIP Tester3 Setting Tool"))
        self.label_3.setText(_translate("Form", "Author: Long.Hou\n"
"\n"
"Email: Long2.Hou@luxshare-ict.com"))
        self.groupBox.setTitle(_translate("Form", "物理串口配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.port_setting), _translate("Form", "串口设置"))
        self.label_4.setText(_translate("Form", "MES Enable:"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.groupBox_2.setTitle(_translate("Form", "Check Process"))
        self.groupBox_3.setTitle(_translate("Form", "Update Result"))
        self.groupBox_4.setTitle(_translate("Form", "Get X Num"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mes_setting), _translate("Form", "MES设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.other_setting), _translate("Form", "其他设置"))
        self.btn_save.setText(_translate("Form", "Save"))
        self.btn_cancel.setText(_translate("Form", "Cancel"))
from Resource.Img import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
